#!/bin/bash
#
# Hugo Mananet 
# 03/09/2018: initial version

Bootstrap: docker

From: phusion/baseimage:0.11


%label
	MAINTAINER Hugo Mananet
	VERSION 2.3.6


%environment
	LANGUAGE=fr_FR.UTF-8 \
	LANG=fr_FR.UTF-8 \
	LC_ALL=fr_FR.UTF-8 \
	
	
%post
	apt-get -y update
	apt-get -y install \
	build-essential \
	wget \ 
	openjdk-8-jre \
	locales && locale-gen fr_FR.UTF-8 \
	export LANGUAGE=fr_FR.UTF-8 \
	export LANG=fr_FR.UTF-8 \
	export LC_ALL=fr_FR.UTF-8 \

	mkdir -p /opt/varscan_2.3.6